
- name: instalando pacotes padroes para debian 
  package: 
   name:
    - htop
    - vim 
    - sysstat 
    - cowsay 
  when: ansible_os_family == "Debian" 

- name: instalando pacotes padores para centos 
  package: 
   name: 
    - epel-release 
    - vim 
    - sysstat
  when: ansible_os_family == "RedHat" 

